# Basic configuration
baseurl: https://atsign.dev/
canonifyURLs: false
disableAliases: true
disableHugoGeneratorInject: true
enableEmoji: true
enableGitInfo: false
enableRobotsTXT: true
languageCode: en_US
paginate: 7
rssLimit: 10

defaultContentLanguage: en

# Sitemap Config
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

taxonomies:
# TODO

# Relative Permalinks
# permalinks:
#   blog: /blog/:title/

minify:
  tdewolff:
    html:
      keepWhitespace: false

# Import doks theme modules
module:
  mounts:
    # ASSETS    
    - source: assets
      target: assets
    - source: node_modules/@hyas/doks/assets
      target: assets
    - source: node_modules/font-awesome
      target: assets
    # vendor assets
    - source: node_modules/flexsearch
      target: assets/js/vendor/flexsearch
    - source: node_modules/katex
      target: assets/js/vendor/katex

    # LAYOUTS
    - source: node_modules/@hyas/doks/layouts
      target: layouts
    - source: layouts
      target: layouts

    # OTHER
    - source: static
      target: static
    - source: content
      target: content
    - source: archetypes
      target: archetypes
    - source: data
      target: data
