
goldmark:
  extensions:
    linkify: false
  parser:
    autoHeadingID: true
    autoHeadingIDType: github
    attribute:
      block: true
      title: true
  renderer:
    unsafe: true

highlight:
  lineNos: true
  lineNumbersInTable: false
  style: dracula

tableOfContents:
  endLevel: 3
  ordered: false
  startLevel: 0
