goldmark:
  extensions:
    linkify: false
  parser:
    autoHeadingID: true
    autoHeadingIDType: github
    attribute:
      block: true
      title: true
  renderer:
    unsafe: true

highlight:
  codeFences: true
  lineNos: true
  lineNumbersInTable: false
  noClasses: false

tableOfContents:
  endLevel: 3
  ordered: false
  startLevel: 0
