main:
  - name: Get Started
    url: /start/
    weight: 1

  - name: Get an atSign
    url: https://my.atsign.com/go
    weight: 2

  - name: GitHub
    url: https://github.com/atsign-foundation
    weight: 3