main:
  - name: Get Started
    url: /start/
    weight: 1

  - name: Get an atSign
    url: https://my.atsign.com/go
    weight: 2

  - name: GitHub
    url: https://github.com/atsign-foundation
    weight: 3

  - name: atsign.com
    url: https://atsign.com
    weight: 4
  - name: Open Issue
    url: https://github.com/atsign-foundation/docs.atsign.com/issues/new/choose
    weight: 5