title: '@platform'
titleSeparator: '-'
titleAddition: Build end-to-end encrypted apps quickly

description: |
  The @platform is the fastest and easiest way to develop peer-to-peer, end-to-end encrypted apps.

alert: false
alertDismissable: true
alertText: |
  My custom banner text here...