name: CheckDeployStaging
on:
  - deployment_status
  - workflow_dispatch

env:
  DEPLOY_URL: "https://dev3.atsign.wtf"

jobs:
  audit:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'gh-pages') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - uses: ./.github/workflows/LighthouseAudit
        with:
          url: ${{ env.DEPLOY_URL }}
